# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import fetch_pb2 as fetch__pb2


class fetchStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Sender = channel.stream_stream(
                '/fetch.fetch/Sender',
                request_serializer=fetch__pb2.Request.SerializeToString,
                response_deserializer=fetch__pb2.Response.FromString,
                )


class fetchServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Sender(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_fetchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Sender': grpc.stream_stream_rpc_method_handler(
                    servicer.Sender,
                    request_deserializer=fetch__pb2.Request.FromString,
                    response_serializer=fetch__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fetch.fetch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class fetch(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Sender(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/fetch.fetch/Sender',
            fetch__pb2.Request.SerializeToString,
            fetch__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
