# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fetch.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66\x65tch.proto\x12\x05\x66\x65tch\"\x84\x01\n\x07Request\x12\x0e\n\x06req_id\x18\x01 \x01(\t\x12\x16\n\x0e\x62\x65nchmark_type\x18\x02 \x01(\t\x12\x17\n\x0fworkload_metric\x18\x03 \x01(\t\x12\x12\n\nbatch_unit\x18\x04 \x01(\x05\x12\x12\n\nbatch_size\x18\x05 \x01(\x05\x12\x10\n\x08\x62\x61tch_id\x18\x06 \x01(\x05\"\xe7\x01\n\x08Response\x12\x0e\n\x06rfw_id\x18\x01 \x01(\t\x12\x15\n\rlast_batch_id\x18\x02 \x01(\t\x12\x14\n\x0crequest_data\x18\x03 \x03(\x05\x12\x0f\n\x07\x61verage\x18\x04 \x01(\x02\x12\x0f\n\x07maximum\x18\x05 \x01(\x02\x12\x0f\n\x07minimum\x18\x06 \x01(\x02\x12\x13\n\x0bstdeviation\x18\x07 \x01(\x02\x12\x14\n\x0cpercentile10\x18\x08 \x01(\x02\x12\x14\n\x0cpercentile50\x18\t \x01(\x02\x12\x14\n\x0cpercentile95\x18\n \x01(\x02\x12\x14\n\x0cpercentile99\x18\x0b \x01(\x02\x32\x36\n\x05\x66\x65tch\x12-\n\x06Sender\x12\x0e.fetch.Request\x1a\x0f.fetch.Response(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fetch_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=23
  _REQUEST._serialized_end=155
  _RESPONSE._serialized_start=158
  _RESPONSE._serialized_end=389
  _FETCH._serialized_start=391
  _FETCH._serialized_end=445
# @@protoc_insertion_point(module_scope)
